name: Main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: python main.py
      - uses: actions/upload-artifact@v4
        with:
          name: archive
          path: "*.apk"
