name: Main

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - run: python main.py
      - uses: actions/upload-artifact@v4
        with:
          name: archive
          path: "*.apk"
